### ISSUE TITLE
PySwitchBot 0.15.0

### ISSUE THREAD

**Issue by CordMaster** [fphammerle/switchbot-mqtt#103]
It seems that the version of PySwitchBot used is a bit out of date and using pybluez. While this is not an issue right now, recent versions have moved to Bleak as the Bluetooth LE backend, and now use an async API as opposed to the blocking one used in 0.12.0. Are there any plans to move to an async loop and support newer versions?

One option would be to move the MQTT package to https://github.com/sbtinstruments/asyncio-mqtt.

I would be more than happy to help out if this is in the roadmap.

Thanks,
--CordMaster

**Comment by fphammerle** [comment]
Hi @CordMaster, thanks for your suggestions! I am following the changes/updates in PySwitchbot. 
Unfortunately, I currently do not have any resources to test the compatibility with the new releases or switch to async mqtt.

**Comment by fphammerle** [comment]
Thanks for suggesting sbtinstruments/asyncio-mqtt.
Before switching to a particular mqtt library, I would need to get an overview of the available async mqtt libs and compare them regarding their interface, ease of integration and size of user base.

**Comment by CordMaster** [comment]
Thanks for the response! I absolutely forgot to thank you for your effort on this wonderful library!!

I did do a little tinkering, and found that it does *work* if (almost) all pySwitchbot commands are run as blocking in their own loop using `asyncio.run(...)`, however there seem to be a bunch of issues with combining threading and asyncio there (I got a bleak error whenever I tried to do two things at once). Additionally, this change also requires a good portion of the unit tests and exception handling code to be rewritten, and I don't want to ruin your 100% coverage 😉. That said, It looks like the newer versions of pySwitchbot would require a switch to an async MQTT library, and a rewrite of most of the codebase. Since all is working well for now (thanks once again!), and I am awfully short on time, I think leaving it as is until a breaking change is made that justifies a huge overhaul is the best option.

Thanks again,
--CordMaster

**Comment by fphammerle** [comment]
Thanks a lot for testing the concurrent/async approach and your feedback!
I hope I'll find time in the upcoming months to modernize switchbot-mqtt in that aspect.
Let's keep the issue open as a reminder :)

**Comment by CordMaster** [comment]
Hello once more!

I did a bit of work on the async transition, and from what I can tell it functions well. There is still a bit of work to be done on error handling, and the unit tests need updating, but if you choose to go with `asyncio_mqtt` you could use this as a base. You can take a look here; just don't want to submit a pr since it really breaks unit tests.

https://github.com/CordMaster/switchbot-mqtt/commit/97e2ac8cc59bddd91aa334d7dd29f4f4f817dd60

Thanks,
--CordMaster

**Comment by fphammerle** [comment]
Great! Thanks a lot for publishing your work and reporting back!

**Comment by fphammerle** [comment]
Main branch now supports pySwitchbot's latest release v0.40.1
(https://github.com/fphammerle/switchbot-mqtt/commit/e964cce38e9586fffac817233eecfb7ba18c75c1 released as pre-release [v4.0.0a0](https://pypi.org/project/switchbot-mqtt/4.0.0a0/#history) )
