### ISSUE TITLE
Possible to send % commando to switchbot

### ISSUE THREAD

**Issue by Diondk** [fphammerle/switchbot-mqtt#59]
Hi,

First of all i would like to thank you for this, its really awesome and a great way to control my switchbot curtains.

My question is would it be possible to send percentage command's to switchbot curtain?

So i would like to be able to set the curtain open for 50% for example. 
Can you point me in the right direction?

Kr,
Dion

**Comment by fphammerle** [comment]
Hi Dion,

Great to hear that `switchbot-mqtt` is useful for you! :)

Unfortunately, setting a specific position is not yet supported.

The feature should be added somewhere here: https://github.com/fphammerle/switchbot-mqtt/blob/v2.2.0/switchbot_mqtt/_actors/__init__.py#L121 by overwriting `_CurtainMotor.mqtt_subscribe`.

Respective home assistant option: https://www.home-assistant.io/integrations/cover.mqtt/#set_position_topic

I'll put it on my todo list. If anyone else is interested in implementing that, please go ahead.

**Comment by fphammerle** [comment]
Feature added in `v3.0.0`: https://github.com/fphammerle/switchbot-mqtt/releases/tag/v3.0.0
