### ISSUE TITLE
Multiple instances using the same MQTT server

### ISSUE THREAD

**Issue by andrey-yantsen** [fphammerle/switchbot-mqtt#70]
Hey, great project, thank you!

I have some issues with the built-in HA integration, and the MQTT adapter saved me a lot of nerves :)

I have a few SwitchBots scattered across the house, and I need to use multiple servers with them for a better connection. From what I can see — it's currently not supported because of this line:
https://github.com/fphammerle/switchbot-mqtt/blob/eaba90003031d481777e65a6a87c946ecdd10f53/switchbot_mqtt/_actors/__init__.py#L36

Please tell me that I'm wrong, and there's a workaround :)

**Comment by fphammerle** [comment]
Hi,

thanks! Great to hear that the project is useful :)

Unfortunately, you are right: The referenced line currently hard-codes the interface's topic prefix.
This should be command-line parameter.
I'll put it on my todo list. If someone else is interested in implementing that, please go ahead.

In the meantime, I can think of two possible (and certainly not pretty) workarounds:
1. Configure your MQTT broker to forward the messages to either of the two switchbot-mqtt clients.
In `mosquitto` e.g. this could be achieved with the `acl_file` option.
2. You fork/clone this project and replace `"homeassistant"` in the referenced line with `os.environ.get("SWITCHBOT_MQTT_TOPIC_PREFIX", "homeasistant")` or similar.

**Comment by andrey-yantsen** [comment]
Ha! I had no idea that it's possible to configure this inside `mosquitto`, thanks!

**Comment by fphammerle** [comment]
Release v3.2.0 provides a new option `--mqtt-topic-prefix`: https://github.com/fphammerle/switchbot-mqtt/tree/v3.2.0#mqtt-topic

**Comment by andrey-yantsen** [comment]
Excellent, thank you!
