### ISSUE TITLE
Use TLS for MQTT broker

### ISSUE THREAD

**Issue by bachya** [fphammerle/switchbot-mqtt#76]
Would it be possible to add the ability to configure MQTT broker TLS?

**Comment by fphammerle** [comment]
Implementation could be done similarly to:
https://github.com/fphammerle/systemctl-mqtt/blob/v0.5.0/systemctl_mqtt/__init__.py#L337
https://github.com/fphammerle/systemctl-mqtt/blob/v0.5.0/systemctl_mqtt/__init__.py#L377
https://github.com/fphammerle/systemctl-mqtt/blob/v0.5.0/systemctl_mqtt/__init__.py#L299

Ideally, TLS should be enabled by default in a separate (major) release.

**Comment by fphammerle** [comment]
@bachya, could you retry with `--mqtt-enable-tls` after upgrading switchbot-mqtt?

**Comment by bachya** [comment]
@fphammerle I upgrade to version 3.1.0 and updated my command to include the `--mqtt-enable-tls` flag:

```
switchbot-mqtt \
  --fetch-device-info \
  --mqtt-enable-tls \
  --mqtt-host REDACTED \
  --mqtt-port 8883 \
  --mqtt-username REDACTED \
  --mqtt-password REDACTED \
  --retries 10
```

...but receive the following error:

```
switchbot-mqtt: error: unrecognized arguments: --mqtt-enable-tls
```

**Comment by fphammerle** [comment]
Great! Thanks for reporting back!
