### ISSUE TITLE
Running on RPI zero

### ISSUE THREAD

**Issue by privatesam** [fphammerle/switchbot-mqtt#8]
I did the setup as per the instructions but running:
    `switchbot-mqtt`
Just gives: 
    ` -bash: switchbot-mqtt: command not found`
Its not clear from the readme that if you're not running from Docker whether or not this needs to be used in a python script or otherwise.

Thanks in advance.

**Comment by fphammerle** [comment]
Did the install command (`pip3 install --user --upgrade switchbot-mqtt`) show any error messages?

Maybe your `PATH` variable is missing `~/.local/bin`:
Could you try running `~/.local/bin/switchbot-mqtt` ?

**Comment by fphammerle** [comment]
> Its not clear from the readme that if you're not running from Docker whether or not this needs to be used in a python script or otherwise.
A python script is not required. `switchbot-mqtt` currently only has a command line interface. So if the install succeeds, you should be able to start `switchbot-mqtt` from a shell

**Comment by privatesam** [comment]
Install went fine.  Just ran `~/.local/bin/switchbot-mqtt` and thats working.  Thank so much for the quick replies and thanks for the software - just what I was looking for!

**Comment by fphammerle** [comment]
Great!

If you prefer the short `switchbot-mqtt` over `~/.local/bin/switchbot-mqtt`, you can add the following command somewhere in your `~/.bash_profile`:
```sh
PATH="$HOME/.local/bin:$PATH"
```
